mosip:
 compliance-toolkit:
  test-cases:
   sbi-test-cases:
    - 
     id: SBI1001
     name: Discover
     description: Validated Discover Response 
     test-order-sequence: 1
     method-name: device
     request-schema: DiscoverRequestSchema
     response-schema: DiscoverResponseSchema
     validators:
      -
       name: SchemaValidator
       description: Validates if response matches the schema
     other-attributes:
        runtime-input:
        purpose:
          - Registration
          - Auth
        biometric-types:
         - Finger
         - Iris
         - Face
        device-sub-types:
         - Slap
         - Single
         - Double
         - Full face
        segments: 
        exceptions:
        sbi-spec-versions:
         - 0.9.5
        device-sub-id: 1
        bio-count: 3
        requested-score: 40     
    - 
     id: SBI1002
     name: Discover1
     description: Valid Discover Request1
     test-order-sequence: 2
     method-name: device
     request-schema: DiscoverRequestSchema
     response-schema: DiscoverResponseSchema
     validators:
      -
       name: SchemaValidator
       description: Validates if response matches the schema
    -
     id: SBI1003
     name: Auth capture - LeftIndex Finger
     description: Valid Auth capture Request for LeftIndex Finger
     test-order-sequence: 3
     method-name: capture
     request-schema: AuthCaptureRequestSchema
     response-schema: AuthCaptureResponseSchema
     other-attributes:
      runtime-input: null
      purpose:
       - Auth
      biometric-types:
       - Finger
      device-sub-types:
       - Single
      segments:
       - LeftIndex
      exceptions: 
      device-sub-id: 0
      bio-count: 1
      requested-score: 40
     validators:
      - 
       name: SchemaValidator
       description: Validates if response matches the schema
    -
     id: SBI1004
     name: Auth capture - Two Finger
     description: Valid Auth capture Request for Two Finger
     test-order-sequence: 4
     method-name: capture
     request-schema: AuthCaptureRequestSchema
     response-schema: AuthCaptureResponseSchema
     other-attributes:
      runtime-input: null
      purpose:
       - Auth
      biometric-types:
       - Finger
      device-sub-types:
       - Single
      segments:
       - LeftIndex
       - LeftMiddle
      exceptions: 
      device-sub-id: 0
      bio-count: 2
      requested-score: 40
     validators:
      - 
       name: SchemaValidator
       description: Validates if response matches the schema
   sdk-test-cases:
    - 
     id: SDK2000
     name: Init Test
     description: Initialise Bio SDK Services 
     test-order-sequence: 1
     method-name: init
     request-schema: InitSDKRequestSchema
     response-schema: InitSDKResponseSchema
     validators:
      -
       name: SchemaValidator
       description: Validates if response matches the schema
     other-attributes:
      modalities: finger,face,iris
    - 
     id: SDK2001
     name: Good face quality
     description: Good face quality 
     test-order-sequence: 2
     method-name: check-quality
     request-schema: CheckQualityRequestSchema
     response-schema: CheckQualityResponseSchema
     validators:
      -
       name: SchemaValidator
       description: Validates if response matches the schema
     other-attributes:
      modalities: face      